[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
to_do_contract = "AeXPYzizpsK4pjooMkfy5f35aujposyF5sH7odrT9hM5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ritikbhatt020/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
